version: '3.8'

services:
  nats-1:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--name nats-1 --cluster nats://0.0.0.0:6222 --cluster_name NATS --routes nats://nats-2:6222,nats://nats-3:6222 --http_port 8222 --js"

  nats-2:
    image: nats:latest
    ports:
      - "4223:4222"
      - "8223:8222"
    command: "--name nats-2 --cluster nats://0.0.0.0:6222 --cluster_name NATS --routes nats://nats-1:6222,nats://nats-3:6222 --http_port 8222 --js"

  nats-3:
    image: nats:latest
    ports:
      - "4224:4222"
      - "8224:8222"
    command: "--name nats-3 --cluster nats://0.0.0.0:6222 --cluster_name NATS --routes nats://nats-1:6222,nats://nats-2:6222 --http_port 8222 --js"
