authorization {
  users = [
    {
      user: publisher
      password: pub123
      permissions {
        publish = ["secure.>"]
        subscribe = "_INBOX.>"
      }
    }
    {
      user: subscriber
      password: sub123
      permissions {
        publish = []
        subscribe = ["secure.>"]
      }
    }
  ]
}
